### ISSUE TITLE
Should the download button respect ytdl-format?

### ISSUE THREAD

**Issue by Samillion** [Samillion/ModernZ#119]
I was having a conversation about this, and it made me realize the current system might be too simple (or too complicated?)

At the moment, the download quality of the video is controlled by the option `ytdlp_format`, which is left empty by default.

But that means, it can download 4K video if it's available, which is not ideal.

To specify download quality you'd need to set something like this in `modernz.conf`
```ini
# Set maximum quality of download to 1080p and codec avc
ytdlp_format=-f bv[height<=1080][vcodec^=avc][ext=mp4]+ba[ext=m4a]/b[ext=mp4][height<=1080]
```

**I was given a suggestion:**
- Left click on download button: use `ytdl-format` as it is set by `mpv.conf` or `yt-dlp`
- Right click on download button: use `ytdlp_format` from `modernz.conf`

That way if you're using a quality control script like [ytdlAuto-Format](https://github.com/Samillion/mpv-ytdlautoformat) or [quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu), it would respect the current formatting you're viewing the video as, to download.

**Comment by Keith94** [comment]
I don't do a lot of downloading YouTube stuff, so I'm not really qualified to say.

My idea for less bloat, what about not forcing any default qualities on modernz side, and just let user handle it in other known ways.

Since the script is about UI, it should just focus on UI stuff. Other technical stuff can be handled by mpv etc. unless the script relies on doing it itself...
