### ISSUE TITLE
The glow effect is not applied while the button is pressed

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#144]
I didn't have a chance yet to compare to other modern players but was curious if it would look better if we kept that glow on while mouse click is held down. What do you think?

**Comment by Samillion** [comment]
Hmmm.. Shouldn't `pressed` have a distinct look though? That's the only thing making me hesitant to add it.

I realize I might be overthinking it, but I've seen PRs halt for months over a discussion whether to use "the" or not lol.

Do you mind if we keep this open for a while to see if it's requested or not before making changes?

**Comment by Keith94** [comment]
I don't mind at all. I'll give it some thought as well to see if I even want it.

**Comment by Samillion** [comment]
By the way, I wasn't rejecting your idea at all. Some changes just get an unexpected reaction. For example, ever since mpv applied select menus like we do on ModernZ, they had to add a way to [restore bindings](https://github.com/mpv-player/mpv/blob/master/etc/restore-osc-bindings.conf) due to complaints.

More customization is always a plus in my book, I merely want to wait and see if this would be an addition that is received well by the mpv masses lol.

**Comment by Anthonyy232** [comment]
I'm all for customization, but my two cents are that it looks better with the glow deactivated when pressed

**Comment by Keith94** [comment]
Thanks for the replies guys. I'm OK with the current behavior.
