### ISSUE TITLE
Add hover effects to window controls

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#180]
Don't know if intentional or oversight, since hover color is not applied to window controls, but held color option is.

**Comment by Samillion** [comment]
It is intentional, yes. The held down effect is applied to all elements:
https://github.com/Samillion/ModernZ/blob/6c1b147282d51d3db5aec6ea69c49447641801b4/modernz.lua#L999-L1001

Window controls have their own hover color effect just to differentiate. Which reminds me, someone requested that I should make the hover colors on window controls configurable. Not sure if I should add it or not. Hmmm.

**Comment by Keith94** [comment]
I kinda like uosc approach where there is a background hover effects applied to them as well.
