### ISSUE TITLE
Can it be more "lenient" for timecode display? 

### ISSUE THREAD

**Issue by jiangzhenjerry** [Samillion/ModernZ#279]
### Expected behavior of the wanted feature

Now that the timecode is moved next to the volume control, it may be hidden if the video window isn't large enough. I find it a little inconvenient.

I have a 27'' 4K monitor for which the system DPI scaling is set to be 150%. To be consistent with the system, I set `scalewindowed = 1.5` for ModernZ. Below is a screenshot where I was playing a 720p video, and as you can see the timecode is not showing. I mean, there is still enough real estate next to the volume bar to show it... :roll_eyes:

<img width="1920" alt="1" src="https://github.com/user-attachments/assets/4d199bd6-afb0-4897-8d07-a6a30439f08e" />

**Comment by Samillion** [comment]
Thank you for the report. Could you please test with this script and let me know the results?

**Test script:** [time_codes_visibility/modernz.lua](https://github.com/Samillion/ModernZ/blob/dev_timecodes_x_position/modernz.lua)
**Commit:** https://github.com/Samillion/ModernZ/commit/faf80ec7e32bc041020b7aa85b4a3efbfc7a25cf

**Changes:**
- Give priority to time codes visibility over volume bar by changing its `x` position depending on available space
- Create offset based on available elements to increase area of visibility for time codes, if possible

**Comment by Samillion** [comment]
If possible, I'd like to see a screenshot of the same mpv window with the test script, please.

Unrelated, but might be useful to you:
Since you have a large monitor realestate, it would maybe be useful to use something like this in your `mpv.conf`
```EditorConfig
# Increase/decrease as you like
autofit=80%x70%
autofit-larger=80%x70%
```

**Comment by xiaoleichen** [comment]
Unrelated, but since DPI scaling is mentioned:

I generally don't like enabling `vidscale=yes/auto`, because UI would appear tiny with small mpv window but gigantic with mpv full screened. So I disable it. 

But with high DPI monitors, the UI is way too small by default. So OK, I set both `scalewindowed=2.0` and `scalefullscreen=2.0`.  Works well.

But with multiple monitors with different DPIs (4k and 1080p for example), the UI looks normal on 4K monitor but huge on 1080p one.

I don't know if there is any good solution to my problem (I suppose there is, given most apps are able to handle this). But since I don't mix monitors with different DPIs now, I'm settled with `vidscale=no`, `scalewindowed=2.0` and `scalefullscreen=2.0`.

**Comment by jiangzhenjerry** [comment]
@Samillion Thank you. It looks great now (Screenshot 1 below) and also works if the playlist button is enabled (Screenshot 2). Appreciated the quick fix!

> Since you have a large monitor realestate, it would maybe be useful to use something like this in your `mpv.conf`

Yes, I used to do something similar (by applying `--hidpi-window-scale`) but then realized I'd rather see the actual video size.

> since I don't mix monitors with different DPIs now, I'm settled with `vidscale=no`, `scalewindowed=2.0` and `scalefullscreen=2.0`

@xiaoleichen This is what I do as well (except I'm doing 1.5 for my monitor and 2.0 for my laptop). Mixed DPI monitors are painful...

<img width="1920" alt="1" src="https://github.com/user-attachments/assets/55d62b7f-0b27-49ec-9477-669ed42f2b16" />
<img width="1920" alt="2" src="https://github.com/user-attachments/assets/d04dd9b7-c4e2-426c-aefe-c88fc96a5f22" />
