### ISSUE TITLE
showinfo button does not work without stats.lua script

### ISSUE THREAD

**Issue by herbrot** [Samillion/ModernZ#3]
**[modernz] stats.lua not found in /scripts folder, disabling showinfo button.**

stats are now buildin and working after removing the _statslua_ references  
	--if user_opts.showinfo then 
		--local statslua_path = mp.command_native({"expand-path", "~~/scripts/stats.lua"})
		--local statslua_file = io.open(statslua_path, "r")

		--if not statslua_file then
			--msg.warn("stats.lua not found in /scripts folder, disabling showinfo button.")
			--user_opts.showinfo = false
		--else
			--io.close(statslua_file)
		--end
	--end

**Comment by Samillion** [comment]
You are absolutely right, and because of your report I was able to confirm something stupid I've done, which was confirmed by guidocell.

Here I thought it wasn't bundled for some reason, but it turns out, long ago, I forgot this in my `mpv.conf` :'D
```properties
load-stats-overlay=no
```

Which caused an error when I try to toggle stats without the stats script:
```
cplayer: Can't find script 'stats' when handling input.
```

Because obviously I disabled it and forgot. I'm ashamed of myself, because I was like "oh, I'll validate this user_opt so others will be careful".

Too funny. xD
