### ISSUE TITLE
"media-title/no-ext" shows "(error)" if the file has a title tag

### ISSUE THREAD

**Issue by Xurdejl** [Samillion/ModernZ#30]

**Comment by Samillion** [comment]
Damn. I completely forgot about that. Will fix default value, thank you for reporting.

**Comment by Samillion** [comment]
I've set `title` in my [modernz.conf](https://github.com/Samillion/mpv-conf/blob/master/script-opts/modernz.conf) to:
```editorconfig
title=${?demuxer-via-network==no:${filename/no-ext}}${?demuxer-via-network==yes:${media-title}}
```

@Keith94 tagging you as well, since you said before you run with `/no-ext`.

Just leaving a note here, in case it's useful to someone in the future.

**Comment by Samillion** [comment]
The error is at mpv side for sure. Using `media-title` is the preferred method, but I genuinely hate it because there are so many video files with mislabeled titles out there, so I use `filename/no-ext` by default.

The problem is, with `/no-ext` on `media-title`, if the video actually has a title tag, `/no-ext` returns an error because it can't find the extension suffix. This should probably be addressed, I'll mention it to the guys at irc later.

Anywho, this mimics my `Stream` auto-profile, but uses the built in demuxer instead of path check.

```editorconfig
# mpv.conf
# default window title
title=${filename/no-ext}

# for streams, grab media-title
# otherwise it would show url params, ie: ?watch=[ID]
[Stream]
	profile-desc=Apply options when opening a URL or a magnet
	profile-cond=get('path', ''):match('^%a+://') or get('path', ''):match('^magnet:')
	profile-restore=copy
	force-seekable=yes
	title=${media-title}
	save-position-on-quit=no
	user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0"
```

**Comment by Keith94** [comment]
>Using media-title is the preferred method, but I genuinely hate it because there are so many video files with mislabeled titles out there

I found this [guess-media-title](https://github.com/zenwarr/mpv-config/blob/master/scripts/guess-media-title.lua) script, which tries to display a nice, clean title output. For example:

- **[Judas] Bleach - Thousand Year Blood War - S17E40.mkv** gets its title displayed as:

<img width="319" height="89" alt="Image" src="https://github.com/user-attachments/assets/55fd95c5-c0d6-4b1c-a535-daa9190e3058" />

- **Leon.The.Professional.1994.REMASTERED.EXTENDED.1080p.BluRay.X264-AMIABLE** becomes just:

<img width="333" height="87" alt="Image" src="https://github.com/user-attachments/assets/6fbd55be-98ce-472f-9a1d-8c26e9f256f2" />

Not sure if it works perfectly in all cases, but I thought it may be helpful.
