### ISSUE TITLE
bug/selection menu below bottom UI elements

### ISSUE THREAD

**Issue by Anthonyy232** [Samillion/ModernZ#36]
Hi, encountered this issue, not selectable due to placement presumably
![image](https://github.com/user-attachments/assets/63b65c90-b06f-41f4-be0f-58e43cb29420)

Config: https://pastebin.com/NVsGMprx

**Comment by Samillion** [comment]
Could you tell me the exact steps that caused this? Because how it is programmed, the OSC is completely disabled until you exit the select menu.

Please update mpv, [console.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/console.lua) and [select.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/select.lua) then try again.

**Comment by Samillion** [comment]
A video demonstrating behavior:

https://github.com/user-attachments/assets/60af24fc-f18f-40ed-8eaa-1f3198ded786

**Comment by Keith94** [comment]
@Anthonyy232 This bug was fixed yesterday in [v0.1.2](https://github.com/Samillion/ModernZ/releases/tag/v0.1.2). If you haven't updated the script, try that first.

**Comment by Anthonyy232** [comment]
Okay, not sure what, but I think one of those fixed it. Thanks
