### ISSUE TITLE
The disabled elements don't follow the same style

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#45]
![mpv_nFbES6YBTb](https://github.com/user-attachments/assets/99292051-39ea-4649-b680-52a34ba47ebc)

i.e. when audio track is unavailable, the volume icon and slider appears less visible/dark gray.

But for the audio and subtitle icons, the button becomes a little less bright but not nearly to the same extent as the volume ones, if that makes sense.

Not sure if they should be adjusted equally to match one or the other, or would a darker appearance look kind of weird/hard to see.

**Comment by Samillion** [comment]
This is driving me crazy because, all of them are supposed to have the same "disabled/enabled" alpha, as handled here:

https://github.com/Samillion/ModernZ/blob/742a4ccf7ba7736de88df1fb773d5e8c0d1923bf/modernz.lua#L717-L727

The only difference is that sub/audio buttons stay regardless. They even use the same `osc_styles.Ctrl3` and the same font.

I'm currently stumped on this, very strange.

**Comment by Xurdejl** [comment]
https://github.com/Samillion/ModernZ/blob/742a4ccf7ba7736de88df1fb773d5e8c0d1923bf/modernz.lua#L1732-L1734

vol_ctrl is missing `ne.off = audio_track_count == 0`. Adding that makes it look the same as the audio and susbtitle icons

**Comment by Samillion** [comment]
Damn, nice find. I looked over it at least 10 times and didn't notice 😆.

Will you PR or should I merge myself? I only ask so that you get full credit for fixing this issue.

**Comment by Xurdejl** [comment]
Sure, I will send a pull request
