### ISSUE TITLE
Scrubbing puts player into a paused state

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#57]
When scrubbing with seekbar and then stopping mouse movement while mouse button held:

default osc: movie keeps playing
modernz:  movie paused until mouse button released

Actually I noticed this while pause-indicator-lite was installed, because the icon shows up the whole time while scrubbing.

Youtube's player behaves similarly, but no pause indicator, and the pause button on bottom corner becomes a play icon while scrubbing.

Could add an option like `pause_when_scrubbing=yes/no` ?

**Comment by Keith94** [comment]
Another behavioral thing, if you click and hold the seekbar handle without mouse movement, the player seeks but it does not pause until mouse moves.

**Comment by Samillion** [comment]
Sorry, just want to make sure I understand correctly. 

Which one are you asking for:
1. An option so the pause indicator doesn't show while seeking with mouse move 
2. An option to not pause while seeking with mouse move

Note: handled in:
https://github.com/Samillion/ModernZ/blob/0fa5431f6143dcc2d79508a41191e7a493e0748c/modernz.lua#L1956-L1959

**Comment by Samillion** [comment]
The reason I ask, if it's about the icon, then `pause_indicator_lite.lua` needs to be edited, if it's about the actual pause state, then it's `modernz.lua`

**Comment by Keith94** [comment]
I think both option would be nice to have. If not too much trouble.

**Comment by Samillion** [comment]
Noted. I will add this `user_opts` behavior in the next update.

I'm on the road at the moment, traveling between states. I apologize in advance if I'm delayed a bit.

**Comment by Keith94** [comment]
Thanks a lot and take your time :)

**Comment by Samillion** [comment]
Off-topic but since indicator is brought up, I added new options to the indicator:

| Option                 | Value       | Description                                                                                                                                   |
|------------------------|-------------|-----------------------------------------------------------------------------------------------------------------------------------------------|
| `flash_play_icon`      | true        | Flash play icon on unpause? (best with pause indicator icon)                                                                                  |
| `flash_icon_timeout`   | 0.3         | How long should the flash last? (seconds)                                                                                                     |
| `flash_icon_bigger_by` | 0           | Increase flash icon size from default by (0-100)                                                                                              |

**Comment by Keith94** [comment]
Good stuff, was the first I noticed was missing.
