### ISSUE TITLE
Tool tip showing hours for short videos

### ISSUE THREAD

**Issue by Keith94** [Samillion/ModernZ#62]
https://github.com/Samillion/ModernZ/pull/50 added new time formatting, but it doesn't apply to seekbar tooltip. it's showing old 00:00:05 for 5 seconds into a 33 second video

**Comment by Samillion** [comment]
Hmmm. This is an actual question, not a rejection. Would we want that changed on the seekbar?

The reason I ask (or hesitate), the seekbar implies accuracy, as in pinpoint. Do you see a scenario where a user would prefer having a full timestamp rather than an omitted one?

I know it's logical to match. I'm just trying to address possible scenarios, to only change if it won't break or affect users in general.

This way at least, if we make the change, we can reference this issue as the reason for the decision. If that makes sense lol.

**Comment by Xurdejl** [comment]
I made a PR with the changes. If the user hovers over a part of the video that exceeds 1 hour, the tooltip will still display the full timestamp (HH:MM:SS), so users won’t lose any information; it only removes the leading '00:'

**Comment by Keith94** [comment]
@Xurdejl Thanks for the fix.

@Samillion I can't think of a good reason for old behavior other than maybe keeping it consistent with mpv itself. IIRC if you set `<input> osd-msg seek 10` the osd shows the full time stamp. Can't confirm right now.
