### ISSUE TITLE
Consider: dynamic time format config flag

### ISSUE THREAD

**Issue by ctlaltdefeat** [Samillion/ModernZ#63]
Dynamic time format was added in https://github.com/Samillion/ModernZ/pull/50/, but some users (me) may not prefer it (confusing at a glance whether a video is 2 minutes or 2 hours long, too used to the old format, etc..).

Perhaps adjustable via config?

**Comment by Samillion** [comment]
Noted. @Xurdejl would you like me to add this as `user_opts` or do you want to do it?

```lua
timestamp_mode = "dynamic",                   -- accepts dynamic, static. (static is default mpv timestamp)
```

**Comment by Xurdejl** [comment]
The leading '00:' felt more like a bug than an intentional design choice since it doesn’t really provide any benefits, just clutter. That’s why I didn’t add an option to display it the old way in the first place. But sure, I can add it as an option

**Comment by Samillion** [comment]
> The leading '00:' felt more like a bug than an intentional design choice since it doesn’t really provide any benefits, just clutter. That’s why I didn’t add an option to display it the old way in the first place. But sure, I can add it as an option

I honestly agree. Since your PR, timestamp has made more sense to me. In fact, one of the first things we learn about elements is only use space you actually need. and the `HH` in a none `HH` file/seek is definitely wasted space.

But preference and old habits die hard. An option to toggle it off (on by default) will satisfy everyone.

Thank you very much.
